import "./blogposts.css";
import { useState } from "react";

function BlogPosts() {
    return (
<div className="allPosts">
    <div className="postOne">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fringilla pharetra tortor, sed dignissim dui condimentum at. Vivamus non dignissim justo, in porta nisi. Proin ac varius nisl. Duis sed justo lobortis, sollicitudin ex non, tempus lorem. Integer mollis in risus a aliquet. Sed nunc sem, volutpat nec pretium sit amet, consectetur id erat. Praesent vulputate ultrices tellus sed dictum. Mauris sed posuere turpis. Vivamus ut rhoncus mi, sit amet vehicula risus. Suspendisse semper condimentum justo sit amet varius. Curabitur at lacus ac tellus dignissim fermentum. Etiam sit amet faucibus diam, eu ultrices nisl. Curabitur pulvinar pellentesque lacus, ut varius urna lacinia vel.

Nullam gravida pulvinar volutpat. Vestibulum id justo ac diam feugiat porttitor. Suspendisse varius, velit sed volutpat fringilla, leo lacus maximus ante, eget varius erat turpis sed metus. Aenean ac purus vitae est congue tincidunt. Donec et vehicula nisl. Nullam ac nibh volutpat, ultricies elit id, viverra metus. Suspendisse lobortis lacus ac eros varius, in ornare dui sollicitudin. Curabitur fermentum auctor est.

Maecenas viverra at felis eu tincidunt. Aenean non tellus justo. Praesent lectus tellus, tempor a elit sed, accumsan placerat tellus. Aenean blandit eros non molestie varius. Donec venenatis arcu sit amet ante finibus interdum. Mauris vestibulum, urna ac dignissim lacinia, nisl nunc efficitur velit, vel cursus velit dui vitae purus. In placerat nec sapien ac maximus. Cras ut leo eu mi convallis convallis et id lacus. Pellentesque convallis dui et orci imperdiet, fringilla suscipit enim elementum.

Nullam sed congue ante, quis dictum dui. Ut nec augue nisl. Maecenas tristique, elit feugiat congue accumsan, dolor lorem egestas tortor, sit amet accumsan libero felis a tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et tincidunt nisi, quis gravida nulla. Curabitur faucibus ligula suscipit urna ornare condimentum. Suspendisse diam mauris, elementum non metus non, porta ultrices nisi. Duis sit amet lobortis turpis, ut pretium leo. Ut felis mi, bibendum ac augue quis, blandit cursus odio.

Mauris tempus dui est, non dictum risus porta non. Morbi vulputate nunc auctor odio congue condimentum. Sed dictum magna sed ipsum ultrices, ut rutrum arcu pharetra. Vivamus mollis faucibus tristique. In finibus tincidunt hendrerit. Vestibulum gravida purus sed sapien facilisis, vel venenatis est tristique. Proin vehicula arcu dolor, nec ullamcorper metus lacinia ac. Aenean id quam efficitur dui gravida pharetra et ut nunc. Suspendisse interdum tellus augue, id rutrum dui efficitur vitae. Aliquam vehicula lobortis ipsum finibus lobortis. Sed congue justo eget sem finibus placerat. Quisque vel mauris id lectus mattis placerat. Vivamus facilisis pretium magna, sed convallis justo posuere in. In commodo pharetra ullamcorper. Nam in malesuada lorem.
    </div>
    <div className="postTwo">
    Bacon ipsum dolor amet short ribs chislic bacon pig leberkas tongue. Brisket picanha doner venison ham hock shoulder jerky chicken burgdoggen chislic. Tri-tip rump alcatra hamburger ribeye. Rump turducken ribeye, ground round cupim tenderloin kielbasa. Shankle alcatra ground round ham hock, brisket kevin buffalo shoulder venison picanha jerky. Prosciutto biltong meatball short ribs flank beef ribs pancetta swine shank pig porchetta drumstick rump strip steak fatback. Strip steak pork loin beef meatball, ground round pastrami shank pig jowl pancetta.

Ham hock rump ground round pig kevin shoulder biltong short loin strip steak bresaola pancetta burgdoggen buffalo jerky. Hamburger corned beef venison, chislic salami turkey shoulder. Chicken buffalo pork salami beef, andouille t-bone hamburger short ribs rump pork loin chislic ham hock kielbasa brisket. Bresaola landjaeger meatball ribeye, ham rump ball tip tongue chislic fatback salami kielbasa brisket. Ribeye sausage porchetta pig, rump flank prosciutto chislic pastrami pork chuck. Sirloin flank jerky corned beef pastrami. Alcatra jowl andouille, ham hock hamburger pork loin picanha.

Ham porchetta pork loin picanha, sausage hamburger sirloin kielbasa spare ribs drumstick landjaeger cupim pig turducken. Rump pork loin alcatra, tri-tip hamburger drumstick sausage meatloaf. Capicola pork chop kevin sirloin alcatra. Frankfurter strip steak beef ribs shankle pork, turkey shank kevin doner. Doner jowl cupim ham, pancetta fatback meatloaf filet mignon. Turkey chuck pastrami hamburger tenderloin. Filet mignon turkey ground round ribeye beef ribs jerky jowl tail picanha andouille frankfurter pork chop burgdoggen chicken ball tip.

Biltong doner drumstick ribeye swine, venison leberkas meatball tenderloin pork chop corned beef brisket pig pork spare ribs. Sausage biltong t-bone, spare ribs beef short ribs flank sirloin picanha cow tenderloin cupim shank corned beef. Cupim jowl rump short loin bacon pork chop. Rump filet mignon landjaeger, shoulder shank venison ground round frankfurter spare ribs. Landjaeger spare ribs beef kielbasa, chuck pork chop bacon boudin salami t-bone fatback sausage jerky pig shoulder. Ham prosciutto ham hock swine leberkas biltong kielbasa porchetta meatball fatback shankle pork spare ribs short loin pork belly.

Pig cupim jerky corned beef kevin pancetta. Fatback andouille spare ribs rump shoulder. Boudin rump landjaeger salami, shankle kevin pancetta pastrami cow hamburger chicken t-bone picanha short loin frankfurter. Brisket swine short ribs, burgdoggen turducken ham bacon shoulder flank. Drumstick shoulder bresaola alcatra chuck ribeye pork loin boudin buffalo beef ribs porchetta meatloaf pork belly sirloin. Pork chop flank ribeye ham pig prosciutto boudin.
    </div>
    <div className="postThree">
    Sriracha pecans pine nuts peach strawberry mango banana bread blood orange smash cauliflower parsley mangos udon noodles green tea morning smoothie bowl picnic salad falafel bites hummus Thai super chili crunchy seaweed sandwiches cinnamon casserole double dark chocolate sweet potato cremini mushrooms creamy cauliflower alfredo sauce. Tasty banana bread chocolate sleepy morning tea Thai sun pepper alfalfa sprouts Sicilian pistachio pesto comforting pumpkin spice latte summer farro platter roasted brussel sprouts. Coriander citrusy lemonade zest cherries street style Thai basil tacos grenadillo soba noodles pineapple salsa black bean chili dip Mexican fiesta mocha chocolate lychee hemp seeds soup kale caesar salad cool cucumbers pinch of yum green tea lime apple vinaigrette tofu red grapes peanut butter crunch cherry bomb pepper chocolate peanut butter dip cumin mint lime taco salsa coconut milk.

Avocado miso dressing second course pomegranate hearty hot maple orange tempeh one bowl avocado dressing drizzle fresh Italian pepperoncini elderberry ginger carrot spiced juice red pepper hearts of palm. Plums spiced peppermint blast banh mi salad rolls orange basmati strawberry spinach salad chickpea crust pizza raspberries cozy cinnamon oatmeal shallots springtime strawberry lavender lemonade Indian spiced Caribbean red habanero hazelnut shiitake rich coconut cream cinnamon toast grapefruit.

Cilantro Bolivian rainbow pepper instant pot peppermint black beans jalapeño tomato and basil guacamole pasta chocolate cookie cookies seasonal green pepper ghost pepper vitamin glow macadamia nut cookies chili. Miso turmeric glazed aubergine red amazon pepper lime habanero golden edamame summer fruit salad burritos hummus falafel bowl banana with dill lemon green onions simmer almond milk chai latte artichoke hearts kung pao pepper cozy butternut cayenne tahini drizzle naga viper strawberries.

Lime mango crisp arugula salad fruit smash samosa peanut butter fall sparkling pomegranate punch portobello mushrooms lemon tahini dressing coconut Chinese five-spice powder oranges bruschetta chili pepper onion. Blackberries blueberry chia seed jam blueberries fiery fruit green bowl ginger tofu balsamic vinaigrette entree green papaya salad crispy iceberg lettuce seitan soy milk coconut rice walnut mushroom tart garlic sriracha noodles enchiladas walnut pesto tart mediterranean luxury bowl picnic creamiest seeds golden cayenne pepper cocoa shaved almonds edamame hummus.

Potato broccoli bento box vine tomatoes almonds chai tea mediterranean crispy smoky maple tempeh glaze mediterranean vegetables cilantro lime vinaigrette butternut mix ginger lemongrass agave green tea cashew roasted peanuts shiitake mushrooms tempeh sweet potato black bean burrito figs. Lemongrass asian pear coconut sugar bananas blueberry pops bite sized spicy appetizer homemade balsamic frosted gingerbread bites apples cranberry spritzer paprika main course salty smoked tofu.

Sweet potato candy cane winter ultimate ultra creamy avocado pesto Thai basil curry raspberry fizz crunchy matcha lentils thyme cherry bomb. Toasted hazelnuts pumpkin couscous sesame soba noodles leek mushroom risotto four-layer Bulgarian carrot mint cool off strawberry mango smoothie spring avocado basil pesto winter cool Thai curry salted tabasco pepper açai creamy cauliflower alfredo peaches.

Overflowing berries lemon lime minty chilies refreshing cucumber splash eating together Southern Italian heat lingonberry chia seeds red lentil curry summertime veggie burgers basil roasted butternut squash earl grey latte green grapes a delicious meal crumbled lentils fig arugula cashew salad dark chocolate kale cherry Thai delightful blueberry scones. Dark and stormy dessert overflowing almond milk scotch bonnet pepper black bean wraps red curry tofu noodles kimchi grains zesty tofu pad thai Malaysian Thai dragon pepper quinoa flatbread dragon fruit lemon red lentil soup salad muffins.
    </div>
</div>
)};
export default BlogPosts;